#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libva-soname1
Version  : 1.8.3
Release  : 3
URL      : https://github.com/intel/libva/archive/libva-1.8.3.tar.gz
Source0  : https://github.com/intel/libva/archive/libva-1.8.3.tar.gz
Summary  : Userspace Video Acceleration (VA) core interface
Group    : Development/Tools
License  : MIT
Requires: compat-libva-soname1-lib = %{version}-%{release}
Requires: compat-libva-soname1-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32egl)
BuildRequires : pkgconfig(32gl)
BuildRequires : pkgconfig(32libdrm)
BuildRequires : pkgconfig(32wayland-client)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xfixes)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xfixes)
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
[![Stories in Ready](https://badge.waffle.io/01org/libva.png?label=ready&title=Ready)](http://waffle.io/01org/libva)
[![Build Status](https://travis-ci.org/01org/libva.svg?branch=master)](https://travis-ci.org/01org/libva)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/11605/badge.svg)](https://scan.coverity.com/projects/01org-libva)

%package lib
Summary: lib components for the compat-libva-soname1 package.
Group: Libraries
Requires: compat-libva-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-libva-soname1 package.


%package lib32
Summary: lib32 components for the compat-libva-soname1 package.
Group: Default
Requires: compat-libva-soname1-license = %{version}-%{release}

%description lib32
lib32 components for the compat-libva-soname1 package.


%package license
Summary: license components for the compat-libva-soname1 package.
Group: Default

%description license
license components for the compat-libva-soname1 package.


%prep
%setup -q -n libva-libva-1.8.3
pushd ..
cp -a libva-libva-1.8.3 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567814101
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%autogen --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1567814101
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libva-soname1
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libva-soname1/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/include/va/va.h
rm -f %{buildroot}/usr/include/va/va_backend.h
rm -f %{buildroot}/usr/include/va/va_backend_egl.h
rm -f %{buildroot}/usr/include/va/va_backend_glx.h
rm -f %{buildroot}/usr/include/va/va_backend_tpi.h
rm -f %{buildroot}/usr/include/va/va_backend_vpp.h
rm -f %{buildroot}/usr/include/va/va_backend_wayland.h
rm -f %{buildroot}/usr/include/va/va_compat.h
rm -f %{buildroot}/usr/include/va/va_dec_hevc.h
rm -f %{buildroot}/usr/include/va/va_dec_jpeg.h
rm -f %{buildroot}/usr/include/va/va_dec_vp8.h
rm -f %{buildroot}/usr/include/va/va_dec_vp9.h
rm -f %{buildroot}/usr/include/va/va_dri2.h
rm -f %{buildroot}/usr/include/va/va_dricommon.h
rm -f %{buildroot}/usr/include/va/va_drm.h
rm -f %{buildroot}/usr/include/va/va_drmcommon.h
rm -f %{buildroot}/usr/include/va/va_egl.h
rm -f %{buildroot}/usr/include/va/va_enc_h264.h
rm -f %{buildroot}/usr/include/va/va_enc_hevc.h
rm -f %{buildroot}/usr/include/va/va_enc_jpeg.h
rm -f %{buildroot}/usr/include/va/va_enc_mpeg2.h
rm -f %{buildroot}/usr/include/va/va_enc_vp8.h
rm -f %{buildroot}/usr/include/va/va_enc_vp9.h
rm -f %{buildroot}/usr/include/va/va_glx.h
rm -f %{buildroot}/usr/include/va/va_tpi.h
rm -f %{buildroot}/usr/include/va/va_version.h
rm -f %{buildroot}/usr/include/va/va_vpp.h
rm -f %{buildroot}/usr/include/va/va_wayland.h
rm -f %{buildroot}/usr/include/va/va_x11.h
rm -f %{buildroot}/usr/lib32/libva-drm.so
rm -f %{buildroot}/usr/lib32/libva-egl.so
rm -f %{buildroot}/usr/lib32/libva-glx.so
rm -f %{buildroot}/usr/lib32/libva-tpi.so
rm -f %{buildroot}/usr/lib32/libva-wayland.so
rm -f %{buildroot}/usr/lib32/libva-x11.so
rm -f %{buildroot}/usr/lib32/libva.so
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-drm.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-egl.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-glx.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-tpi.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-wayland.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva-x11.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32libva.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-drm.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-egl.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-glx.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-tpi.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-wayland.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva-x11.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libva.pc
rm -f %{buildroot}/usr/lib64/libva-drm.so
rm -f %{buildroot}/usr/lib64/libva-egl.so
rm -f %{buildroot}/usr/lib64/libva-glx.so
rm -f %{buildroot}/usr/lib64/libva-tpi.so
rm -f %{buildroot}/usr/lib64/libva-wayland.so
rm -f %{buildroot}/usr/lib64/libva-x11.so
rm -f %{buildroot}/usr/lib64/libva.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-drm.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-egl.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-glx.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-tpi.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-wayland.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva-x11.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libva.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libva-drm.so.1
/usr/lib64/libva-drm.so.1.4000.0
/usr/lib64/libva-egl.so.1
/usr/lib64/libva-egl.so.1.4000.0
/usr/lib64/libva-glx.so.1
/usr/lib64/libva-glx.so.1.4000.0
/usr/lib64/libva-tpi.so.1
/usr/lib64/libva-tpi.so.1.4000.0
/usr/lib64/libva-wayland.so.1
/usr/lib64/libva-wayland.so.1.4000.0
/usr/lib64/libva-x11.so.1
/usr/lib64/libva-x11.so.1.4000.0
/usr/lib64/libva.so.1
/usr/lib64/libva.so.1.4000.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libva-drm.so.1
/usr/lib32/libva-drm.so.1.4000.0
/usr/lib32/libva-egl.so.1
/usr/lib32/libva-egl.so.1.4000.0
/usr/lib32/libva-glx.so.1
/usr/lib32/libva-glx.so.1.4000.0
/usr/lib32/libva-tpi.so.1
/usr/lib32/libva-tpi.so.1.4000.0
/usr/lib32/libva-wayland.so.1
/usr/lib32/libva-wayland.so.1.4000.0
/usr/lib32/libva-x11.so.1
/usr/lib32/libva-x11.so.1.4000.0
/usr/lib32/libva.so.1
/usr/lib32/libva.so.1.4000.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libva-soname1/COPYING
